# Deploy custom build of bahmniapps
# turn this one or off by adding this role the "all.yml" file

- name: Download bahmniapps from remote location as zip file
  get_url: url=https://github.com/endtb/openmrs-module-bahmniapps/releases/download/2.3.0/endtb-bahmniapps-0.89-44.zip dest=/tmp/bahmniapps.zip

- name: Clear out existing bahmniapps content
  file: path=/opt/bahmni-web/etc/bahmniapps state=absent

- name: Recreate the bahmniapps directory
  file: path=/opt/bahmni-web/etc/bahmniapps state=directory

- name: Extract contents of zip file into bahmniapps directory
  unarchive: src=/tmp/bahmniapps.zip dest=/opt/bahmni-web/etc/bahmniapps/ copy=no

- name: Set permissions on bahmniapps dir
  file: path=/opt/bahmni-web/etc/bahmniapps owner=bahmni group=bahmni mode=0755 recurse=yes

- name: Remove downloaded zip file
  file: path=/tmp/bahmniapps.zip state=absent

